[tool.poetry]
name = "python-cuda12"
version = "0.1.0"
description = ""
authors = ["Daniel Fahey <daniel.fahey@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.1.1"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
